### ISSUE TITLE
calibur: command not found

### ISSUE THREAD

**Issue by Wes-V3** [kalngyk/calibur#1]
After `make`, I type `calibur` but got calibur: command not found.
I also tried to type `sh> calibur`, and it just stuck here.
I use Ubuntu 20.04.4 LTS, if it helps.
btw, is calibur also apply to RNA structure cluster?

**Comment by kalngyk** [comment]
Perhaps the current directory is not in your PATH variable. Can you try with ./calibur and let me know how it goes?

calibur should work with any structures specified in the PDB format. But if you need a more confident answer please let me know the context (maybe a paper reference) which you work with.

**Comment by Wes-V3** [comment]
> Perhaps the current directory is not in your PATH variable. Can you try with ./calibur and let me know how it goes?
> 
> calibur should work with any structures specified in the PDB format. But if you need a more confident answer please let me know the context (maybe a paper reference) which you work with.

Thank you for your quick reply!
I try with the `./calibur`, but there were no outputs.
```
(base) ~/calibur$ calibur
calibur: command not found
(base) ~/calibur$ ./calibur
(base) ~/calibur$
```
and when I try with `sh> calibur` and `sh> ./calibur`, it stops there. I wait for some time and then I type ctrl+C to break.
```
(base) ~/calibur$ sh> ./calibur
^C
(base) ~/calibur$ sh> calibur
^C

```

**Comment by Wes-V3** [comment]
> > Perhaps the current directory is not in your PATH variable. Can you try with ./calibur and let me know how it goes?
> > calibur should work with any structures specified in the PDB format. But if you need a more confident answer please let me know the context (maybe a paper reference) which you work with.
> 
> Thank you for your quick reply! I try with the `./calibur`, but there were no outputs.
> 
> ```
> (base) ~/calibur$ calibur
> calibur: command not found
> (base) ~/calibur$ ./calibur
> (base) ~/calibur$
> ```
> 
> and when I try with `sh> calibur` and `sh> ./calibur`, it stops there. I wait for some time and then I type ctrl+C to break.
> 
> ```
> (base) ~/calibur$ sh> ./calibur
> ^C
> (base) ~/calibur$ sh> calibur
> ^C
> ```

I redownload the code from github and everything works fine now.
I downloaded from the sourceforge earlier. It seems there may be some diffrences. https://sourceforge.net/projects/calibur/files/calibur/Release-2021-11-29/calibur.zip/download

Thank you for your reply again and for your wonderful job!

**Comment by kalngyk** [comment]
Sorry for the lost time in troubleshooting this. But I am glad that you managed to solve it.

You're right -- calibur.zip is meant for compiling using Code::Blocks on Windows so it could be a little different. I will think of a way to convey this on Sourceforge. Sorry that it wasn't clear at all.
