### ISSUE TITLE
Segmentation fault (core dumped) on Linux and std::bad_alloc on Windows

### ISSUE THREAD

**Issue by Wes-V3** [kalngyk/calibur#2]
On Windows:
```
C:\Users\11\Downloads\calibur.win32 (1)>calibur.exe -o pdblist.txt
Filtering on
Signature mode on
Using chains 'A', 'C', ' ' in PDB files
Read 60 decoy names
Estimating threshold range... complete
Estimated threshold range = [9999999.00000, 0.00000]
Most frequent distance = 9833330.00000
10.00000 percent distances below nan
Finding threshold to keep 35.93041% edges
Threshold = nan
Reading decoys with signature mode on and filter mode on
Read 60 decoys. Filtered 0 outlier decoys.
Decoys read in 0.01000 s
Initialized 60 decoys.
Use of SCUD's bound off
Using MATRIX mode
Auxiliary clustering... 98.3%
AuxiliaryClustering... completed in 0.02600 s
 completedcoys' neighbors... completed 98.3%
Finding and removing largest clusters...terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
On Linux:
```
(base) :~/calibur-main$ ./calibur-lite /calibur-main/predicted_structures/pdblist.txt 
Filtering on
Signature mode on
Using chains 'A', 'C', ' ' in PDB files
Read 60 decoy names
Segmentation fault (core dumped)
```
Using calibur in Rosetta on Linux:
```
(base) :~$ $ROSETTA/calibur.linuxgccrelease -pdb_list /pdblist
core.init: Checking for fconfig files in pwd and ./rosetta/flags 
core.init: Rosetta version: rosetta.binary.linux.release-315 r315 2022.12+release.a4d7970 a4d79705213bc2acd6b51e370eddbb2738df6866 https://www.rosettacommons.org 2022-03-22T15:27:26.590656
core.init: command: /Rosetta/main/source/bin/calibur.linuxgccrelease -pdb_list /pdblist
basic.random.init_random_generator: 'RNG device' seed mode, using '/dev/urandom', seed=-678486154 seed_offset=0 real_seed=-678486154
basic.random.init_random_generator: RandomGenerator:init: Normal mode, seed=-678486154 RG_type=mt19937
core.init: Resolved executable path: /Rosetta/main/source/build/src/release/linux/5.4/64/x86/gcc/9/default/calibur.default.linuxgccrelease
core.init: Looking for database based on location of executable: /Rosetta/main/database/
Using C-alphas #1-end
Filtering on
Signature mode off
Using chains 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ' in PDB files
Read 578 decoy names
Estimating threshold range...

AN INTERNAL ERROR HAS OCCURED. PLEASE SEE THE CONTENTS OF ROSETTA_CRASH.log FOR DETAILS.


Segmentation fault (core dumped)
```
I'm using calibur to clustering RNA structures.
[pdblist.txt](https://github.com/kalngyk/calibur/files/8862115/pdblist.txt)

**Comment by kalngyk** [comment]
This is embarrassing, but it appears that calibur ran out of memory to allocate.

I wonder if it is possible for me to look at the decoys data that caused the problem? That will help me confirm if it really is a memory allocation problem, and perhaps find a workaround.

**Comment by Wes-V3** [comment]
> This is embarrassing, but it appears that calibur ran out of memory to allocate.
> 
> I wonder if it is possible for me to look at the decoys data that caused the problem? That will help me confirm if it really is a memory allocation problem, and perhaps find a workaround.

Of course. Thank you!
Becasue Github doesn't support uploading .pdb file, so I change the suffix to .md
[R1126_ME.pred1.min.md](https://github.com/kalngyk/calibur/files/8862533/R1126_ME.pred1.min.md)
[R1126_ME.pred2.min.md](https://github.com/kalngyk/calibur/files/8862534/R1126_ME.pred2.min.md)
[R1126_ME.pred3.min.md](https://github.com/kalngyk/calibur/files/8862535/R1126_ME.pred3.min.md)
[R1126_ME.pred4.min.md](https://github.com/kalngyk/calibur/files/8862536/R1126_ME.pred4.min.md)
[R1126_ME.pred5.min.md](https://github.com/kalngyk/calibur/files/8862537/R1126_ME.pred5.min.md)
[R1126_ME.pred6.min.md](https://github.com/kalngyk/calibur/files/8862538/R1126_ME.pred6.min.md)
[R1126_ME.pred7.min.md](https://github.com/kalngyk/calibur/files/8862539/R1126_ME.pred7.min.md)
[R1126_ME.pred8.min.md](https://github.com/kalngyk/calibur/files/8862540/R1126_ME.pred8.min.md)
[R1126_ME.pred9.min.md](https://github.com/kalngyk/calibur/files/8862541/R1126_ME.pred9.min.md)
[R1126_ME.pred10.min.md](https://github.com/kalngyk/calibur/files/8862542/R1126_ME.pred10.min.md)
[R1126_PK.pred1.min.md](https://github.com/kalngyk/calibur/files/8862543/R1126_PK.pred1.min.md)
[R1126_PK.pred2.min.md](https://github.com/kalngyk/calibur/files/8862544/R1126_PK.pred2.min.md)
[R1126_PK.pred3.min.md](https://github.com/kalngyk/calibur/files/8862545/R1126_PK.pred3.min.md)
[R1126_PK.pred4.min.md](https://github.com/kalngyk/calibur/files/8862546/R1126_PK.pred4.min.md)
[R1126_PK.pred5.min.md](https://github.com/kalngyk/calibur/files/8862548/R1126_PK.pred5.min.md)
[R1126_PK.pred6.min.md](https://github.com/kalngyk/calibur/files/8862550/R1126_PK.pred6.min.md)
[R1126_PK.pred7.min.md](https://github.com/kalngyk/calibur/files/8862551/R1126_PK.pred7.min.md)
[R1126_PK.pred8.min.md](https://github.com/kalngyk/calibur/files/8862552/R1126_PK.pred8.min.md)
[R1126_PK.pred9.min.md](https://github.com/kalngyk/calibur/files/8862553/R1126_PK.pred9.min.md)
[R1126_PK.pred10.min.md](https://github.com/kalngyk/calibur/files/8862554/R1126_PK.pred10.min.md)
[R1126_RF.pred1.min.md](https://github.com/kalngyk/calibur/files/8862556/R1126_RF.pred1.min.md)
[R1126_RF.pred2.min.md](https://github.com/kalngyk/calibur/files/8862557/R1126_RF.pred2.min.md)
[R1126_RF.pred3.min.md](https://github.com/kalngyk/calibur/files/8862558/R1126_RF.pred3.min.md)
[R1126_RF.pred4.min.md](https://github.com/kalngyk/calibur/files/8862560/R1126_RF.pred4.min.md)
[R1126_RF.pred5.min.md](https://github.com/kalngyk/calibur/files/8862561/R1126_RF.pred5.min.md)
[R1126_RF.pred6.min.md](https://github.com/kalngyk/calibur/files/8862562/R1126_RF.pred6.min.md)
[R1126_RF.pred7.min.md](https://github.com/kalngyk/calibur/files/8862563/R1126_RF.pred7.min.md)
[R1126_RF.pred8.min.md](https://github.com/kalngyk/calibur/files/8862564/R1126_RF.pred8.min.md)
[R1126_RF.pred9.min.md](https://github.com/kalngyk/calibur/files/8862565/R1126_RF.pred9.min.md)
[R1126_RF.pred10.min.md](https://github.com/kalngyk/calibur/files/8862566/R1126_RF.pred10.min.md)
[R1126TS125_1.md](https://github.com/kalngyk/calibur/files/8862567/R1126TS125_1.md)
[R1126TS125_2.md](https://github.com/kalngyk/calibur/files/8862568/R1126TS125_2.md)
[R1126TS125_3.md](https://github.com/kalngyk/calibur/files/8862569/R1126TS125_3.md)
[R1126TS125_4.md](https://github.com/kalngyk/calibur/files/8862570/R1126TS125_4.md)
[R1126TS125_5.md](https://github.com/kalngyk/calibur/files/8862571/R1126TS125_5.md)
[R1126TS131_1.md](https://github.com/kalngyk/calibur/files/8862572/R1126TS131_1.md)
[R1126TS131_2.md](https://github.com/kalngyk/calibur/files/8862573/R1126TS131_2.md)
[R1126TS131_3.md](https://github.com/kalngyk/calibur/files/8862575/R1126TS131_3.md)
[R1126TS131_4.md](https://github.com/kalngyk/calibur/files/8862576/R1126TS131_4.md)
[R1126TS131_5.md](https://github.com/kalngyk/calibur/files/8862577/R1126TS131_5.md)
[R1126TS229_1.md](https://github.com/kalngyk/calibur/files/8862578/R1126TS229_1.md)
[R1126TS229_2.md](https://github.com/kalngyk/calibur/files/8862579/R1126TS229_2.md)
[R1126TS229_3.md](https://github.com/kalngyk/calibur/files/8862580/R1126TS229_3.md)
[R1126TS229_4.md](https://github.com/kalngyk/calibur/files/8862581/R1126TS229_4.md)
[R1126TS229_5.md](https://github.com/kalngyk/calibur/files/8862582/R1126TS229_5.md)
[R1126TS239_1.md](https://github.com/kalngyk/calibur/files/8862583/R1126TS239_1.md)
[R1126TS239_2.md](https://github.com/kalngyk/calibur/files/8862584/R1126TS239_2.md)
[R1126TS239_3.md](https://github.com/kalngyk/calibur/files/8862585/R1126TS239_3.md)
[R1126TS239_4.md](https://github.com/kalngyk/calibur/files/8862586/R1126TS239_4.md)
[R1126TS239_5.md](https://github.com/kalngyk/calibur/files/8862587/R1126TS239_5.md)
[R1126TS245_1.md](https://github.com/kalngyk/calibur/files/8862588/R1126TS245_1.md)
[R1126TS245_2.md](https://github.com/kalngyk/calibur/files/8862589/R1126TS245_2.md)
[R1126TS245_3.md](https://github.com/kalngyk/calibur/files/8862590/R1126TS245_3.md)
[R1126TS245_4.md](https://github.com/kalngyk/calibur/files/8862591/R1126TS245_4.md)
[R1126TS245_5.md](https://github.com/kalngyk/calibur/files/8862592/R1126TS245_5.md)
[R1126TS489_1.md](https://github.com/kalngyk/calibur/files/8862593/R1126TS489_1.md)
[R1126TS489_2.md](https://github.com/kalngyk/calibur/files/8862594/R1126TS489_2.md)
[R1126TS489_3.md](https://github.com/kalngyk/calibur/files/8862595/R1126TS489_3.md)
[R1126TS489_4.md](https://github.com/kalngyk/calibur/files/8862596/R1126TS489_4.md)
[R1126TS489_5.md](https://github.com/kalngyk/calibur/files/8862597/R1126TS489_5.md)

**Comment by Wes-V3** [comment]
Of course! Thank you!
[RNA_structures.zip](https://github.com/kalngyk/calibur/files/8862647/RNA_structures.zip)


> This is embarrassing, but it appears that calibur ran out of memory to allocate.
> 
> I wonder if it is possible for me to look at the decoys data that caused the problem? That will help me confirm if it really is a memory allocation problem, and perhaps find a workaround.

**Comment by kalngyk** [comment]
A quick glance showed a negative threshold RMSD value. This could be due to a floating point value overflow, which implies that the input decoys could be very dissimilar.

But give me some time to confirm and fix this. I will update you ASAP.

**Comment by kalngyk** [comment]
This is what happened.

calibur uses only the coordinates of the lines marked with `CA` (carbon alpha) in the pdb files. For example, in the following, only the coordinates of the second line is used.

<pre>
ATOM      1  N   VAL A 238      11.251  -9.834  -2.389  1.00  0.00           N
ATOM      2  CA  VAL A 238      11.896  -8.749  -3.115  1.00  0.00           C
ATOM      3  C   VAL A 238      13.369  -8.689  -2.728  1.00  0.00           C
</pre>

However, the decoy files you tested contain no `CA` elements. Because of this, all the RMSD computed are set to NaN. This resulted in no cluster discovered, causing calibur to go into an infinite loop.

To solve this quickly, replace the symbol of the lines which you want to use as CA elements with `CA`. For example, the following bash command would substitute all the lines of symbols `C1'`, `C2'`, ..., `C5'`, to `CA`

`for F in *.pdb; do cat $F |sed 's/ 0 / A /' |sed "s/C.'/CA /" > output/$F; done`

(The command will also change the chain from `0` to `A`, since calibur defaults to use only the chains `A`, `C`, or `" "`.)

**Comment by Wes-V3** [comment]
> This is what happened.
> 
> calibur uses only the coordinates of the lines marked with `CA` (carbon alpha) in the pdb files. For example, in the following, only the coordinates of the second line is used.
> 
> ATOM      1  N   VAL A 238      11.251  -9.834  -2.389  1.00  0.00           N
> ATOM      2  CA  VAL A 238      11.896  -8.749  -3.115  1.00  0.00           C
> ATOM      3  C   VAL A 238      13.369  -8.689  -2.728  1.00  0.00           C
> However, the decoy files you tested contain no `CA` elements. Because of this, all the RMSD computed are set to NaN. This resulted in no cluster discovered, causing calibur to go into an infinite loop.
> 
> To solve this quickly, replace the symbol of the lines which you want to use as CA elements with `CA`. For example, the following bash command would substitute all the lines of symbols `C1'`, `C2'`, ..., `C5'`, to `CA`
> 
> `for F in *.pdb; do cat $F |sed 's/ 0 / A /' |sed "s/C.'/CA /" > output/$F; done`
> 
> (The command will also change the chain from `0` to `A`, since calibur defaults to use only the chains `A`, `C`, or `" "`.)

This solves my problem, thank you for your quick reply and solution.
If possible, could you provide an option like "-RNA" to make it better applicable to clustering RNA structures? In any case, thanks for your excellent work!

**Comment by kalngyk** [comment]
Thanks for the suggestion. But I am not yet familiar with RNA notations so I am not sure how to make the change.
OTOH, I have added an option to allow renaming of the atom for comparison, as well as an option to allow all chains.
I hope these changes make the analysis of RNAs easier.
